#!/bin/bash

# Credential Generation Script for Echobase
# Generates .env.secrets with secure random values for JWT_SECRET and MCP_API_KEY.
# Config lives in .env (tracked in git). Only secrets go in .env.secrets (gitignored).

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=================================================${NC}"
echo -e "${GREEN}  Echobase Credential Generation Script${NC}"
echo -e "${GREEN}=================================================${NC}"
echo ""

# Ensure we're running from the project root (where .env lives)
if [ ! -f .env ]; then
    echo -e "${RED}Error: .env not found. Run this script from the project root.${NC}"
    exit 1
fi

# Check if .env.secrets already exists
if [ -f .env.secrets ]; then
    echo -e "${YELLOW}Warning: .env.secrets file already exists!${NC}"

    # In CI environments, always regenerate without prompting
    if [ -n "$CI" ]; then
        echo "Running in CI environment, regenerating credentials..."
        cp .env.secrets .env.secrets.backup 2>/dev/null || true
    else
        read -p "Do you want to regenerate credentials? This will overwrite existing values (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo -e "${RED}Aborted. Keeping existing .env.secrets file.${NC}"
            exit 0
        fi
        # Backup existing .env.secrets
        cp .env.secrets .env.secrets.backup
        echo -e "${GREEN}Backed up existing .env.secrets to .env.secrets.backup${NC}"
    fi
fi

# Function to generate a secure random password
generate_password() {
    local length=${1:-32}
    openssl rand -base64 48 | tr -d "=+/" | cut -c1-${length}
}

echo "Generating secure random credentials..."
echo ""

# Generate secrets
JWT_SECRET=$(generate_password 64)
MCP_API_KEY=$(generate_password 60)

# Write .env.secrets
{
    echo "# Generated by generate-credentials.sh on $(date)"
    echo "# WARNING: This file contains secrets. Never commit to version control!"
    echo ""
    echo "# JWT secret for token signing/verification"
    echo "JWT_SECRET=${JWT_SECRET}"
    echo ""
    echo "# MCP Server API key"
    echo "MCP_API_KEY=${MCP_API_KEY}"
} > .env.secrets

# Set restrictive permissions on .env.secrets file
chmod 600 .env.secrets

echo -e "${GREEN}Credentials generated successfully!${NC}"
echo ""

echo -e "${GREEN}Created .env.secrets with generated credentials${NC}"
echo -e "${GREEN}Set file permissions to 600 (owner read/write only)${NC}"
echo ""

# Display credential summary (without showing actual passwords)
echo -e "${YELLOW}=================================================${NC}"
echo -e "${YELLOW}  Credential Summary${NC}"
echo -e "${YELLOW}=================================================${NC}"
echo ""
echo "Generated Secrets:"
echo "  - JWT Secret: [GENERATED - ${#JWT_SECRET} characters]"
echo "  - MCP API Key: [GENERATED - ${#MCP_API_KEY} characters]"
echo ""
echo -e "${YELLOW}=================================================${NC}"
echo ""

echo -e "${GREEN}Next Steps:${NC}"
echo "1. Review the generated .env.secrets file"
echo "2. Run: docker compose up -d"
echo "3. Your services will use the secure credentials automatically"
echo ""
echo -e "${RED}IMPORTANT SECURITY NOTES:${NC}"
echo "  - .env.secrets is in .gitignore — never commit it"
echo "  - .env is tracked in git and contains NO secrets"
echo "  - Keep a secure backup of your credentials"
echo ""
echo -e "${GREEN}Credential generation complete!${NC}"
